version: "2"
services:
#####################################################
###############   ANALYSIS PHASE ####################
#####################################################
  crawler:
    build:
      context: analysis
      dockerfile: ./Dockerfile_crawler
    command: [crawl, '--amqp-url=amqp://guest:guest@rabbitmq:5672','--queue=images', '--fp=100', '--ps=10','--mi=100']
    labels:
      - "constraint:node==didoUbuntu"
    # Schedule containers on a specific node
    # environment:
    #   - "constraint:node==node-1"

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: on-failure:3
    restart: always
    #container_name: rabbitmq
    ports:
      - 8082:15672
    # networks:
    #   - core-net
    volumes:
      - /var/lib/rabbitmq

  scanner:
    build:
      context: analysis
      dockerfile: ./Dockerfile_scanner
    command: [run, '--images-url=http://images_server:3000/api/images', '--queue=images', '--key=images.scan', '--software-url=http://software_server:3001/api/software', '--rmi']
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

#####################################################
###############   DISCOVERY PHASE ####################
#####################################################

  # Web Software
  software_server:
    build: discovery/softwareService/software_server
    ports:
      - "3001:3001"
    labels:
      - "constraint:node==didoUbuntu"

  # Software database
  software_db:
    image: mongo:3
    #container_name: software_mongo
    volumes:
      - /data/db
    labels:
      - "constraint:node==didoUbuntu"

  # webapp:
  #   build: discovery/webapp
  #   command: []



#####################################################
###############   STORAGE PHASE ####################
#####################################################

  # Web images
  images_server:
    build: storage/images_server
    #image: dofinder/imagesserver:latest
    container_name: images_server
    #restart: always
    restart: on-failure:3
    ports:
      - "3000:3000"
    depends_on:
     - images_db
    # links:
    #  - images_db

  # Images database
  images_db:
    image: mongo:3
    container_name: images_mongo
    volumes:
      - /data/db

#
# networks:
#    docker-finder:
#      external: true
