version: "2"
services:
#####################################################
###############   ANALYSIS PHASE ####################
#####################################################
  crawler:
    build:
      context: analysis
      dockerfile: ./Dockerfile_crawler
    command: [crawl, '--save-url=/data/crawler/lasturl.txt', '--amqp-url=amqp://guest:guest@rabbitmq:5672', '--images-url=http://images_server:3000/api/images/', '--queue=images'] #,'--mi=100'] #, '--fp=100', '--ps=10']
    volumes:
        - /data/crawler/

    # labels:
    #   - "constraint:node==didoUbuntu"
    # networks:
    #   - docker-finder
    # Schedule containers on a specific node
    # environment:
    #   - "constraint:node==node-1"

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    #restart: on-failure:3
    restart: always
    #container_name: rabbitmq
    ports:
      - 8082:15672
    volumes:
      - /var/lib/rabbitmq
    # labels:
    #   - "constraint:node==didoUbuntu"
    # networks:
    #    - docker-finder

  scanner:
    build:
      context: analysis
      dockerfile: ./Dockerfile_scanner
    command: [run, '--images-url=http://images_server:3000/api/images/', '--queue=images', '--key=images.scan', '--software-url=http://software_server:3001/api/software', '--rmi']
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # networks:
    #     - docker-finder

  checker:
      build:
        context: analysis
        dockerfile: ./Dockerfile_checker
      command: [run, '--interval=30','--path-logging=/data/crawler/log/stats.log','--images-url=http://images_server:3000/api/images/', '--queue=images', '--key=images.scan','--amqp-url=amqp://guest:guest@rabbitmq:5672']
      volumes:
         - /dockerfinder/checker/log:/data/crawler/log

#####################################################
###############   DISCOVERY PHASE ####################
#####################################################

  # Web Software
  software_server:
    build: discovery/softwareService/software_server
    ports:
      - "3001:3001"
    depends_on:
      - software_db

  # Software database
  software_db:
    image: mongo:3
    volumes:
      - /data/db  # /data/db is the deafult directory where mogno stores the databases.


#####################################################
###############   STORAGE PHASE ####################
#####################################################

  # Web images
  images_server:
    build: storage/images_server
    #image: dofinder/imagesserver:latest
    #container_name: images_server
    #restart: always
    restart: on-failure:3
    ports:
      - "3000:3000"
    depends_on:
    - images_db

  # Images database
  images_db:
    image: mongo:3
    #container_name: images_mongo
    volumes:
      - /data/db
    # /data/db is the deafult directory where mogno container store the databases.


#####################################################
###############   MANAGEMENT PHASE ####################
#####################################################

  monitor:
    #container_name: monitor
    build: management
    ports:
      - "3002:3002"
    # labels:
    #   - "constraint:node==didoUbuntu"


# networks:
#    docker-finder:
#      external: true
