---
version: '2'
services:
  images_server:
    build: imagesService/images_server/
    image: dofinder/imagesserver:latest
    container_name: images_server
    ports:
    - 3000:3000
    depends_on:
    - images_db
    links:
    - images_db
    networks:
    - core-net
  images_db:
    image: mongo:3
    container_name: images_mongo
    volumes:
    - "/data/dofinder/images:/data/db"
    networks:
    - core-net
  software_server:
    build: softwareService/software_server/
    container_name: software_server
    image: dofinder/softwareserver:latest
    ports:
      - "3001:3001"
    depends_on:
     - software_db
    links:
     - software_db        # it is resolved by internal DNS, must be set in the app.js express config
    networks:
     - core-net

  software_db:
    image: mongo:3
    container_name: software_mongo
    volumes:
     - /data/dofinder/software:/data/db
    networks:
     - core-net

networks:
  core-net:
    external: true
