version: '2'
services:
  images_server:
    build: images_server
    image: dofinder/imagesserver:latest
    container_name: images_server
    #restart: always
    restart: on-failure:3
    ports:
      - "3000:3000"
    depends_on:
     - images_db
    links:
     - images_db
    networks:
      - core-net

  images_db:
    image: mongo:3
    container_name: images_mongo
    volumes:
      - /data/db
    networks:
      - core-net

networks:
  core-net:
    external: true
