version: '2'
services:
  app:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/code
    depends_on:
     - mongo

  mongo:
    image: mongo:3

networks:
  default:
    external:
      name: dofinder-network